### ISSUE TITLE
jraiser打包

### ISSUE THREAD

**Issue by simonbaker** [heeroluo/jraiser#2]
请问，怎么把多个index.js打包成一个js？
因为现在是这样的：在开发模式(debug=true)，某个页面加载的js大概有28个，发布时候(debug=false)需要加载的js是13个。
谢谢啦。

**Comment by heeroluo** [comment]
请修改package.settings，在list里面增加一条规则：
```
{ "target": "^/", "excepts": ["^(?!/)"] }
```
这样可以把类库以外的模块合并起来

**Comment by simonbaker** [comment]
增加了这两天规则，试了下，没反应。
后来，我想了下，html页面中的require是根据依赖来加载不同的js文件。但是想不明白你说的这两条规则具体的怎么来打包成一个文件。
之前，在gulpfile文件中，都是指定好需要打包的文件(1.js、2.js)，同时也把输出的文件指定好(dist/app.js)。
所以，还要继续请教下你。

**Comment by heeroluo** [comment]
为了更好的帮助您解决问题，请详细告诉我：
1. JS目录结构。
2. loader的配置。
3. 打包的时候用的是jraiser-mdk吗？

**Comment by simonbaker** [comment]
要不，你加下我QQ：675036196。
谢谢了。

**Comment by heeroluo** [comment]
已解决
